In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold


In [34]:
df = pd.read_csv('D:/Data Sience/Project/Dt_02/clean data/Clean_data.csv')

In [35]:
df.dropna()

DIABETE3  SEX  _AGEG5YR  EDUCA  _BMI5  _BMI5CAT  GENHLTH  PHYSHLTH  \
0              0    2         9      4   1855         2        4        88   
1              0    2        14      6   1695         1        2        88   
2              0    2        13      6   2141         2        2        88   
3              0    1         8      6   2585         3        2         2   
4              0    1        10      4   2510         3        2        88   
...          ...  ...       ...    ...    ...       ...      ...       ...   
512818         0    1         3      3   2647         3        2        88   
512819         0    2        11      4   2780         3        3        88   
512820         0    1         1      5   3797         4        1        88   
512821         0    1         9      2   2403         2        2        88   
512822         0    1         6      5   3054         4        4        88   

        _TOTINDA  EXERANY2  ...  SMOKDAY2  _RFSMOK3  DRNKANY5  ALCDAY5  \
0              2         2  ...         1         2         1      103   
1              1         1  ...         3         1         1      101   
2              2         2  ...         3         1         1      107   
3              1         1  ...         3         1         1      210   
4              1         1  ...         3         1         1      215   
...          ...       ...  ...       ...       ...       ...      ...   
512818         1         1  ...         3         1         1      201   
512819         2         2  ...         3         1         1      204   
512820         1         1  ...         1         2         1      203   
512821         2         2  ...         1         2         1      103   
512822         2         2  ...         1         2         1      203   

        AVEDRNK2  DRNK3GE5  _RFBING5  CVDSTRK3  CVDINFR4  CVDCRHD4  
0              2        88         1         2         2         2  
1              1        88         1         2         2         2  
2              2        88         1         2         2         2  
3              2        88         1         2         2         2  
4              4        88         1         2         2         2  
...          ...       ...       ...       ...       ...       ...  
512818        24         1         2         2         2         2  
512819         2        88         1         2         2         2  
512820         8         3         2         2         2         2  
512821        18         3         2         2         2         2  
512822         2         1         2         2         2         1  

[512823 rows x 21 columns]

In [36]:
x = df.drop('DIABETE3', axis= 1)
y = df['DIABETE3']

In [37]:
y.value_counts(normalize=True)

DIABETE3
0    0.904326
1    0.095674
Name: proportion, dtype: float64

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)

In [39]:
rf_classifier = RandomForestClassifier(bootstrap=True, class_weight="balanced_subsample", random_state=42)

In [40]:
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(class_weight='balanced_subsample', random_state=42)

In [41]:
y_pred = rf_classifier.predict(x_test)

In [42]:
conf_matrix = confusion_matrix(y_test, y_pred)



In [43]:
class_report = classification_report(y_test, y_pred)


In [44]:
conf_matrix

array([[91474,  1278],
       [ 9049,   764]], dtype=int64)

In [45]:
class_report

'              precision    recall  f1-score   support\n\n           0       0.91      0.99      0.95     92752\n           1       0.37      0.08      0.13      9813\n\n    accuracy                           0.90    102565\n   macro avg       0.64      0.53      0.54    102565\nweighted avg       0.86      0.90      0.87    102565\n'

In [46]:
print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Confusion Matrix:
 [[91474  1278]
 [ 9049   764]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.99      0.95     92752
           1       0.37      0.08      0.13      9813

    accuracy                           0.90    102565
   macro avg       0.64      0.53      0.54    102565
weighted avg       0.86      0.90      0.87    102565



In [47]:
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)

In [49]:
imputer = SimpleImputer(strategy='mean')

In [50]:
x_train_imputed = imputer.fit_transform(x_train)
x_test_imputed = imputer.transform(x_test)

In [51]:
smote = SMOTE(random_state=42)
x_train_res, y_train_res = smote.fit_resample(x_train_imputed, y_train)

In [52]:
rf_classifier = RandomForestClassifier(bootstrap=True, class_weight="balanced_subsample", random_state=42)

In [53]:
rf_classifier.fit(x_train_res, y_train_res)


RandomForestClassifier(class_weight='balanced_subsample', random_state=42)

In [54]:
y_pred = rf_classifier.predict(x_test_imputed)


In [55]:
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [56]:
print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Confusion Matrix:
 [[90921  1831]
 [ 8774  1039]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.98      0.94     92752
           1       0.36      0.11      0.16      9813

    accuracy                           0.90    102565
   macro avg       0.64      0.54      0.55    102565
weighted avg       0.86      0.90      0.87    102565

